In [19]:
import pandas as pd

df = pd.read_csv(r"C:\Data Analyst Projects\customer-churn\data\Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [20]:
df.drop(['customerID'], axis=1, inplace=True, errors='ignore')

In [22]:
if 'TotalCharges' in df.columns:
    df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
else:
    print("⚠️ TotalCharges column not found. Creating from MonthlyCharges * tenure...")
    df['TotalCharges'] = df['MonthlyCharges'] * df['tenure']

In [23]:
df['Churn'] = df['Churn'].str.strip().map({'Yes': 1, 'No': 0})

In [24]:
cat_cols = df.select_dtypes(include=['object']).columns
print(cat_cols)

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='object')

In [25]:
binary_cols = ['Partner','Dependents','PhoneService','PaperlessBilling']
for col in binary_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

In [26]:
df = pd.get_dummies(df, columns=['InternetService','PaymentMethod','Contract'], drop_first=True)

In [28]:
df['MonthlyCostPerService'] = df['MonthlyCharges'] / (df['tenure']+1)

In [29]:
df.to_csv("../data/churn_cleaned.csv", index=False)

In [30]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,TotalCharges,Churn,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_One year,Contract_Two year,MonthlyCostPerService
0,Female,0,1,0,1,0,No phone service,No,Yes,No,...,29.85,0,False,False,False,True,False,False,False,14.925000
1,Male,0,0,0,34,1,No,Yes,No,Yes,...,1889.50,0,False,False,False,False,True,True,False,1.627143
2,Male,0,0,0,2,1,No,Yes,Yes,No,...,108.15,1,False,False,False,False,True,False,False,17.950000
3,Male,0,0,0,45,0,No phone service,Yes,No,Yes,...,1840.75,0,False,False,False,False,False,True,False,0.919565
4,Female,0,0,0,2,1,No,No,No,No,...,151.65,1,True,False,False,True,False,False,False,23.566667

In [31]:
#Average Monthly Spend per Tenure
df['AvgMonthlySpend'] = df['TotalCharges'] / (df['tenure'] + 1)

In [34]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,Churn,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_One year,Contract_Two year,MonthlyCostPerService,AvgMonthlySpend
0,Female,0,1,0,1,0,No phone service,No,Yes,No,...,0,False,False,False,True,False,False,False,14.925000,14.925000
1,Male,0,0,0,34,1,No,Yes,No,Yes,...,0,False,False,False,False,True,True,False,1.627143,53.985714
2,Male,0,0,0,2,1,No,Yes,Yes,No,...,1,False,False,False,False,True,False,False,17.950000,36.050000
3,Male,0,0,0,45,0,No phone service,Yes,No,Yes,...,0,False,False,False,False,False,True,False,0.919565,40.016304
4,Female,0,0,0,2,1,No,No,No,No,...,1,True,False,False,True,False,False,False,23.566667,50.550000